name: release_brew

on:
  push:
    tags:
      - 'v*'
      - '!*test*'
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Set up Go 1.14
      id: go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: go build -o unity-loader cmd/unity-loader/main.go && tar -zcvf unity-loader-${{ github.ref }}.tar.gz unity-loader README.md LICENSE

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: unity-loader
        asset_name: unity-loader
        asset_content_type: application/gzip
